<section class="mt-3 card card-body">
    <h1>Novo Catagoria</h1>
    
    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input type="text" name="nome" id="nome" class="form-control mb-3" >

                <button class="btn btn-primary">Pronto</button>

            </form>
        </div>
        <div class="col"></div>
    </div>
</section>