<section class="mt-3 card card-body">
    <h1>Gerenciar Categoria</h1>

    <div>
        <a href="/categorias/cadastrar" class="btn btn-primary">Novo Categoria</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Categoria</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach ($categorias ?? [] as $categoria){
                    echo "
                    <tr>
                        <td>{$categoria->id}</td>
                        <td>{$categoria->nome}</td>
                        <td>
                            <a href='/categorias/editar?id={$categoria->id}' class='btn btn-outline-warning btn-sm'>Editar</a>
                            <a href='/categorias/excluir?id={$categoria->id}' class='btn btn-outline-danger btn-sm'>Excluir</a>
                        </td>
                    </tr>";
                }
            ?>
        </tbody>
    </table>
</section>